# %%

# %%
# 4*np.pi/(3*(4*np.pi)**(3/2))


def mesh_gen_reg_force():
    """ """
    import sys

    sys.path.append("./")
    from src.python.utilities import make_output_dir
    from src.python.half_edge_base_unit_torus import DoughnutFactory
    import numpy as np
    from python.half_edge_mesh import HalfEdgeMeshBase
    from src.python.half_edge_base_brane import Brane
    from src.python.half_edge_base_viewer import MeshViewer
    from src.python.half_edge_base_ply_tools import MeshConverterBase

    ##############################################################
    # Generates triangle meshes for unit area torii.
    # Output files are labeled by number of faces in the mesh.

    # 1) Raw meshes are first generated by DoughnutFactory.
    # 2) Delaunay triangulations are computed by flipping edges
    # 3) smoothing is applied to the mesh
    # 4) Vertices are projected onto surface
    ##############################################################
    # Directory to save ply files and numpy binary files
    output_dir = "./output/torus_mesh_gen2"
    # Directory to save images/movie of smoothing
    image_dir = f"{output_dir}/temp_images"
    # Ratio of radii and number of samples
    # Rphi:Rpsi=Nphi:Npsi=scale_phi:scale_psi
    # Nphi = scale_phi * 2**resolution
    # Npsi = scale_psi * 2**resolution
    # num_vertices = Nphi * Npsi
    # num_faces = 2 * Nphi * Npsi
    #           = 2 * scale_phi * scale_psi * 4**resolution
    # num_edges = 3 * Nphi * Npsi
    scale_phi = 3
    scale_psi = 1
    resolution_min = 4
    resolution_max = 6
    # Iterations of steps 2-4
    smooth_iters = 100
    dt = 5e-3
    view = {
        "azimuth": 45.0,
        "elevation": 54.7,
        "distance": 2.0,
        "focalpoint": np.array([0.0, 0.0, 0.0]),
    }
    # view = (45.0, 54.73561031724534, 2.0394837232982357, np.array([0.0, 0.0, 0.0]))

    Nfaces = [
        2 * scale_phi * scale_psi * 4**p
        for p in range(resolution_min, resolution_max + 1)
    ]
    surfname = f"unit_torus_{scale_phi}_{scale_psi}"
    plys_raw = [f"{surfname}_raw_{num_faces:06d}_he.ply" for num_faces in Nfaces]
    samples_raw = [f"{surfname}_raw_{num_faces:06d}_he.npz" for num_faces in Nfaces]
    plys_smooth = [f"{surfname}_smooth_{num_faces:06d}_he.ply" for num_faces in Nfaces]
    samples_smooth = [
        f"{surfname}_smooth_{num_faces:06d}_he.npz" for num_faces in Nfaces
    ]

    make_output_dir(output_dir, overwrite=True)

    f = DoughnutFactory(scale_phi=scale_phi, scale_psi=scale_psi, name=surfname)
    surface_area = 1.0  # = 4*np.pi**2*f.Rphi*f.Rpsi
    interior_volume = 2 * np.pi**2 * f.Rphi * f.Rpsi**2
    spontaneous_face_areas = [surface_area / _ for _ in Nfaces]
    spontaneous_edge_lengths = [
        np.sqrt(4 * _ / np.sqrt(3)) for _ in spontaneous_face_areas
    ]
    spontaneous_volumes = [interior_volume for _ in Nfaces]

    ###############
    # R = 1.0
    kBT = 6.25e-3
    tau = 1.28e5
    bending_modulus = 20 * kBT

    # spontaneous_volume = 4 * np.pi * R**3 / 3
    length_reg_stiffness = 80 * kBT
    area_reg_stiffness = 5e5 * kBT / surface_area
    volume_reg_stiffness = 7.5e5 * kBT / interior_volume
    linear_drag_coeff = 1e-1 * kBT * tau / surface_area

    brane_kwargs = {
        "length_reg_stiffness": length_reg_stiffness,
        "area_reg_stiffness": area_reg_stiffness,
        "volume_reg_stiffness": volume_reg_stiffness,
        "bending_modulus": bending_modulus,
        "spontaneous_curvature": 0.0,
        "linear_drag_coeff": linear_drag_coeff,
        # "spontaneous_face_area": spontaneous_face_area,
        # "spontaneous_volume": spontaneous_volume,
    }
    print(f"{brane_kwargs=}")
    ###############

    def better_mesh(m):

        num_flips = m.flip_non_delaunay()
        # m.smooth_by_shifts()
        xyz_coord_V0 = m.xyz_coord_V.copy()
        Fa = m.Farea_harmonic()
        F = Fa
        Fv = m.Fvolume_harmonic()
        F += Fv
        # print(f"Fa={np.linalg.norm(Fa, np.inf)}")
        # print(f"Fv={np.linalg.norm(Fv, np.inf)}")
        # Ft = m.Ftether()
        # F += Ft
        Fb = m.Fbend_analytic()
        F += Fb
        print(f"F={np.linalg.norm(F, np.inf)}")
        v = 0
        fp_mag = 1e2
        fp = fp_mag * m.normal_other_weighted_v(v)
        F[v] += fp
        Dxyz_coord_V = dt * F / m.linear_drag_coeff
        print(f"Dxyz_coord_V={np.linalg.norm(Dxyz_coord_V, np.inf)}")
        xyz_coord_V = xyz_coord_V0 + Dxyz_coord_V
        # xyz_coord_V = f.project_to_torus(*xyz_coord_V.T)
        m.xyz_coord_V = xyz_coord_V
        # vecs = 0.25 * F / np.linalg.norm(F, np.inf)
        vecs = np.zeros_like(F)
        vecs[v] += 0.25 * fp / np.linalg.norm(fp)
        return m.xyz_coord_V, vecs

    for _, p in enumerate(range(resolution_min, resolution_max + 1)):
        brane_kwargs["spontaneous_face_area"] = spontaneous_face_areas[_]
        brane_kwargs["spontaneous_edge_length"] = spontaneous_edge_lengths[_]
        brane_kwargs["spontaneous_volume"] = spontaneous_volumes[_]
        num_faces = Nfaces[_]
        image_dir = f"{output_dir}/temp_images_{num_faces:06d}"
        print("-------------------------------------")
        print(f"initializing mesh_converter at resolution {p=}")
        f.init_mesh_converter_at_resolution_p(p)
        c = f.mesh_converter[p]
        # num_faces = f.num_faces(p)
        # ply_path = f"{output_dir}/{surfname}_raw_{num_faces:06d}_he.ply"
        ply_path = f"{output_dir}/{plys_raw[_]}"
        # samples_path = f"{output_dir}/{surfname}_raw_{num_faces:06d}_he.npz"
        samples_path = f"{output_dir}/{samples_raw[_]}"
        print(f"writing {ply_path=}")
        c.write_he_ply(ply_path, use_binary=True)
        print(f"writing {samples_path=}")
        c.write_he_samples(
            path=samples_path, compressed=False, chunk=False, remove_unchunked=False
        )
        print("smoothing samples...")
        make_output_dir(image_dir, overwrite=False)
        # m = HalfEdgeMeshBase(*c.he_samples)
        m = Brane(*c.he_samples, **brane_kwargs)
        mv = MeshViewer(
            m,
            # figsize=(480, 480),
            figsize=(720, 720),
            image_dir=image_dir,
            view=view,
            # show_vector_fields=False,
        )
        mv.vec_field_apply_fun_iter(better_mesh, num_iters=smooth_iters)

        # ply_smooth = f"{output_dir}/{surfname}_smooth_{num_faces:06d}_he.ply"
        ply_path = f"{output_dir}/{plys_smooth[_]}"
        # samples_smooth = f"{output_dir}/{surfname}_smooth_{num_faces:06d}_he.npz"
        samples_path = f"{output_dir}/{samples_smooth[_]}"

        print(f"initializing smooth mesh_converter at resolution {p=}")
        c = MeshConverterBase.from_he_samples(*m.he_samples, compute_vf_stuff=False)
        print(f"writing {ply_path=}")
        c.write_he_ply(ply_path, use_binary=True)
        print(f"writing {samples_smooth=}")
        c.write_he_samples(
            path=samples_path, compressed=False, chunk=False, remove_unchunked=False
        )


# mesh_gen0()
mesh_gen_reg_force()
# %%
# import numpy as np
# from src.python.half_edge_base_brane import Brane
# from src.python.half_edge_base_viewer import MeshViewer
#
# ply_paths_raw = [f"{output_dir}/{_}" for _ in plys_raw]
# samples_paths_raw = [f"{output_dir}/{_}" for _ in samples_raw]
# ply_paths_smooth = [f"{output_dir}/{_}" for _ in plys_smooth]
# samples_paths_smooth = [f"{output_dir}/{_}" for _ in samples_smooth]
#
# ply = ply_paths_smooth[0]
# samples = samples_paths_smooth[2]
# # b = Brane.from_he_ply(ply)
# b = Brane.load_he_samples(samples)
# points = b.xyz_coord_V
# # vectors = b.Fbend_analytic()
# # Fdensity = b.Fbend_density()
# # Fdensity *= 0.5 / np.linalg.norm(Fdensity, np.inf)
# # n = b.normal_other_weighted_V()
# # vectors = np.einsum("i, ij->ij", Fdensity, n)
# # A = b.area_F()
# # L = b.length_H()
# Fb = b.Fbend_analytic()
# Fa = b.Farea_harmonic()
# Fv = b.Fvolume_harmonic()
# Ft = b.Ftether()
#
# F = Fb
# vectors = 0.25 * F / np.linalg.norm(F, np.inf)
# mv = MeshViewer(b)
# mv.add_vector_field(points, vectors)
# mv.plot()
#
#
# def iter_fun(m):
#     dt = 1e-2
#     m.euler_step(dt)
#
#
# # %%
# def compress_and_save():
#     pass
#
#
# #
# # %%
# # p = 5
# # m0 = HalfEdgeMeshBase(*f.mesh_converter[p].he_samples)
# # m = HalfEdgeMeshBase(*f.mesh_converter[p].he_samples)
# #
# #
# # # m.flip_non_delaunay()
# #
# #
# # err, num_flips = better_mesh(m)
# # m0.num_faces
# # print(f"{err=}, {num_flips=}")
# # # mv0 = MeshViewer(m0)
# # # mv0.plot()
# # m0.total_area_of_faces()
# #
# # mv = MeshViewer(m)
# # mv.apply_fun_iter(better_mesh, num_iters=50)
# #
# # ply_raw = "./output/torus_mesh_gen/unit_torus_3_1_raw_098304_he.ply"
# # ply_smooth = "./output/torus_mesh_gen/unit_torus_3_1_smooth_098304_he.ply"
# # ply_raw = "./output/torus_mesh_gen/unit_torus_3_1_raw_024576_he.ply"
# # ply_smooth = "./output/torus_mesh_gen/unit_torus_3_1_smooth_024576_he.ply"
# # # ply = "./data/ply/binary/unit_sphere_163842_he.ply"
# # # m = HalfEdgeMeshBase.from_he_ply(ply_raw)
# # m = HalfEdgeMeshBase.from_he_ply(ply_smooth)
# # mv = MeshViewer(m, figsize=(480, 480), show_half_edges=True)
# # mv.plot()
# # %%
# from mayavi import mlab
#
# mlab.view()
